### ISSUE TITLE
Change from Deciles to number of bins 

### ISSUE THREAD

**Issue by Avichaicha** [tensorbored/kds#1]
HI, your package is great and I really enjoy using it. 
my suggestion is to change the fix 10 bins option to a parameter given by user because in many cases users interesting in model performance in the high score areas (top 5% , top 2%..)

**Comment by tensorbored** [comment]
@Avichaicha great input, a parameter can be created for number of bins. I am occupied with work currently, so if you want quick resolution please make a pull request. Let me know.

**Comment by tensorbored** [comment]
Update the code. 

Added a new parameter `change_deciles=10` in `decile_table` function.

`change_deciles (int, optional): The number of partitions for creating the table can be changed. Defaults to '10' for deciles.`
